### ISSUE TITLE
提两条建议

### ISSUE THREAD

**Issue by superbobogithub** [codingZero/XRCarouselView#1]
1、如果我的手势一直往左滑动，是不是应该图片0到图片2呢？
2、pageControl是不是加上事件会更完善些！

**Comment by codingZero** [comment]
@superbobogithub 关于第一点，是不是说，我使劲一滑，会连续滚动好几张？如果这样的话，貌似没办法做，分页效果就是这样，除非取消分页，我看了很多app，好像都不可以。关于第二点，之前考虑过，但是跑在真机上，手太大不太好点，所以就没弄
