### ISSUE TITLE
cocopods集成，使用网上图片的时候，每次都崩-[__NSArrayMinsertObject:atIndex:]:object cannot be nil

### ISSUE THREAD

**Issue by lxlxl3691** [codingZero/XRCarouselView#12]
我不用cocopods，使用你之前的版本就不崩

**Comment by codingZero** [comment]
@lxlxl3691 看你报错信息，应该是你往数组中插入了一个nil

**Comment by codingZero** [comment]
@lxlxl3691 看你报错信息，应该是你往数组中插入了一个nil，你自己检查下，或者你把代码发来，我给你看看

**Comment by lxlxl3691** [comment]
我的代码就是复制你Demo中的代码，只有在使用cocoapods集成你的框架的时候，使用网络图片，就会崩报这个错误，如果使用本地图片就不崩（本地图片也是复制你的代码和图片）。如果把框架下载下来，拖到工程里，就不会出现这个问题

**Comment by codingZero** [comment]
@lxlxl3691 你这个问题好奇怪，我刚刚用cocoapods集成试了下，没有问题，你看一下，你用cocoapods集成的时候，是不是占位图片没有弄下来啊

**Comment by lxlxl3691** [comment]
就是占位图片的问题，我把代码改了就可以了，但是为什么我集成的时候展位图片没有跟着下载下来

**Comment by codingZero** [comment]
@lxlxl3691  不太清楚，我这边试了几次都是可以把占位图片下载下来的
