### ISSUE TITLE
自动轮播，崩溃。

### ISSUE THREAD

**Issue by mikelrmb** [codingZero/XRCarouselView#15]
hi，看了你的自动轮播感觉写的很不错，但是我将我自己写的库切换成你的库后，发现广告崩溃。

错误日志：-[UIView setImage:]: unrecognized selector sent to instance 0x170395af0
崩溃在这句代码：￼￼                    _pageControl.currentPage = (_currIndex + 1) % self.images.count;
我在首页添加了自动轮播，在不停的push和pop的操作后，有几率会崩溃。

已在生命周期做Stop Timer 和Start Timer处理，望回复，并解决。

**Comment by codingZero** [comment]
@mikelrmb 你好，能把代码发一份给我么？这个bug我没有遇到过。。。

**Comment by mikelrmb** [comment]
@codingZero  项目比较大，代码不好贴，问题也不好复线，我是将XRCarouseIView放在TableView的HeadView中。

**Comment by mikelrmb** [comment]
@codingZero 这个我是使用XRCarouseIView的具体方法
- (void)setUpAdvertisment{
  self.height += 160;
  self.carouselView = [XRCarouselView carouselViewWithImageArray:self.adArr describeArray:nil];
  self.carouselView.frame = self.frame;
  self.carouselView.height = 160;
  self.carouselView.delegate = self;
  _carouselView.time = 10;
  [_carouselView setPageImage:[FSStatusHelper imageNamed:@"banndr_paging_nor"] andCurrentPageImage:[FSStatusHelper imageNamed:@"banndr_paging_highlighted"]];
  _carouselView.pagePosition = PositionBottomCenter;
  [self addSubview:self.carouselView];
  _collectionView.top = self.carouselView.bottom;
  }

**Comment by mikelrmb** [comment]
@codingZero 这个我是使用XRCarouseIView的具体方法
- (void)setUpAdvertisment{
  self.height += 160;
  
    self.carouselView = [XRCarouselView carouselViewWithImageArray:self.adArr describeArray:nil];
  
    self.carouselView.frame = self.frame;
  
    self.carouselView.height = 160;
  
    self.carouselView.delegate = self;
  
    _carouselView.time = 10;
  
    [_carouselView setPageImage:[FSStatusHelper imageNamed:@"banndr_paging_nor"] andCurrentPageImage:[FSStatusHelper imageNamed:@"banndr_paging_highlighted"]];
  
    _carouselView.pagePosition = PositionBottomCenter;
  
    [self addSubview:self.carouselView];
  
    _collectionView.top = self.carouselView.bottom;
  }

**Comment by codingZero** [comment]
@mikelrmb  我按照你说的方式写了一遍，没有崩溃，你这个是最新版本的吗？你下最新版本的试试

**Comment by mikelrmb** [comment]
@codingZero  使用了你最近代码 还是会崩溃
崩溃原因还是之前这个：
-[UIView setImage:]: unrecognized selector sent to instance 0x174394b80

**Comment by codingZero** [comment]
@mikelrmb 这个我真没办法了，毕竟我没遇到过，所以我也没办法调试，看你报错信息应该是试图调用UIView的setImage方法，这种错误一般不难找的。。。

**Comment by mikelrmb** [comment]
大致知道原因了 是因为我有个视频，全屏后会调用LayoutSubviews 你那边也被调用了 重新StartTimer了。有没办法进行判断呢？

**Comment by mikelrmb** [comment]
@codingZero

**Comment by codingZero** [comment]
@mikelrmb  你可以把我的layoutsubview方法里的starttime方法去掉 ，然后你手动调用

**Comment by codingZero** [comment]
@mikelrmb 我这边在运行过程中重新调用了一下layoutSubViews方法，没有问题，要不你把我的layoutsubview方法里的starttime去掉 ，然后你手动启动定时器

**Comment by mikelrmb** [comment]
@codingZero 嗯 我现在版本就是这么处理的，但是就是希望这个是独立控件，外面不要做判断。后来才又来问你。

**Comment by mikelrmb** [comment]
@codingZero ..当我没说 还是没好

**Comment by codingZero** [comment]
@mikelrmb 额，我无能为力了，你要是方便的话，可以新建一个工程，把这部分代码扒出来，然后发给我，我来帮你看看

**Comment by mikelrmb** [comment]
找到原因了，我主页和发现都是使用了你的控件，他们都继承与一个父类，父类网络请求来了之后，调用了两次startTimer 出现了问题
