### ISSUE TITLE
发现个bug

### ISSUE THREAD

**Issue by wanghongbo** [codingZero/XRCarouselView#16]
感谢作者提供这么优秀的开源工程: ）
bug：
两张滚动图片，当滚动到第一张时候，切换到另一个界面（比如另一个tabbar），过4s钟再切回来，发现pageControl已经指示第二张图了，但是图片显示的还是第一张图，没有切到第二张图。经过我调试，发现把changeToNext方法内容用dispatch_async(dispatch_get_main_queue,...)包起来可以解决这个问题: )

**Comment by codingZero** [comment]
@wanghongbo 谢谢反馈，刚试了下，确实有这个问题，我把self.otherImageView.image = self.images[self.nextIndex]这句代码放到changeToNext前面也能解决这个问题。

**Comment by spliang** [comment]
作者你好。我在使用时也发现一个问题，具体表现为：如果图片为网络图片，则一直显示占位图片，不显示网络图像。同样的网络环境下，上一版本无此问题。

**Comment by codingZero** [comment]
@spliang 你好，出现这种情况应该是你网速太慢，或者你的图片链接不正确，你打开沙盒看看Library-Caches-XRCarousel这个文件夹里面有没有图片，如果没有，那就是图片下载不成功
