### ISSUE TITLE
分享到其他app 返回的时候广告栏出现白色

### ISSUE THREAD

**Issue by EasonGaoDevelop** [codingZero/XRCarouselView#17]
从其他app 返回的时候，会出现广告栏空白

**Comment by codingZero** [comment]
@EasonGaoDevelop  你好，你是指从其他app返回后轮播图为空白么？我试了下，我这边demo是可以的

**Comment by EasonGaoDevelop** [comment]
是的，我觉得是挂起app的时候，nstimer 继续在轮播

**Comment by codingZero** [comment]
@EasonGaoDevelop  那你挂起的时候让它暂停试试
