### ISSUE TITLE
placeholder的照片, 最好用UIColor畫一個出來

### ISSUE THREAD

**Issue by ipalm0423** [codingZero/XRCarouselView#2]
使用者若直接把.h輸入進來，沒有輸入到placeholder的照片，就會發生錯誤
- (void)setImageArray:(NSArray _)imageArray{
  _imageArray = imageArray;
  _images = [NSMutableArray array];
  for (int i = 0; i < imageArray.count; i++) {
      if ([imageArray[i] isKindOfClass:[UIImage class]]) {
          [_images addObject:imageArray[i]];
      } else if ([imageArray[i] isKindOfClass:[NSString class]]){
        *_  [_images addObject:# **[UIImage imageNamed:@"placeholder"]];**

**Comment by codingZero** [comment]
占位图片跟文件都是放在同一个文件夹下的，无论使用cocoapods导入还是手动拖入XRCarouselView文件夹，图片都会跟着一起导入，应该不会出现你说的那个问题

**Comment by codingZero** [comment]
@ipalm0423 占位图片跟文件都是放在同一个文件夹下的，无论使用cocoapods导入还是手动拖入XRCarouselView文件夹，图片都会跟着一起导入，应该不会出现你说的那个问题

**Comment by ipalm0423** [comment]
可能是我直接拉取程式(.h, .m的關係)

**Comment by ipalm0423** [comment]
或許也可以多個property  給使用者自選placeholder
