### ISSUE TITLE
占位图未提供修改接口.

### ISSUE THREAD

**Issue by urmyfaith** [codingZero/XRCarouselView#20]
占位图未提供修改接口.

可以提供一个修改接口,然后在.m 里给个默认的设置.
如果设置了就使用修改的,
如果没有设置就使用默认的占位图.

对于使用 Pod 的用户来说,直接修改源文件?

**Comment by codingZero** [comment]
@urmyfaith  感谢反馈，已更新

**Comment by urmyfaith** [comment]
@codingZero  把 pod 也更新了吧.
