### ISSUE TITLE
照片顯示方式，最好也能加入@property

### ISSUE THREAD

**Issue by ipalm0423** [codingZero/XRCarouselView#3]
[_currImageView setContentMode:**UIViewContentModeScaleAspectFill]**;
[_otherImageView setContentMode:**UIViewContentModeScaleAspectFill];**
_currImageView.clipsToBounds = YES;
_otherImageView.clipsToBounds = YES;

**Comment by codingZero** [comment]
@ipalm0423  谢谢，这个建议很好
