### ISSUE TITLE
pageControl 位置计算错乱

### ISSUE THREAD

**Issue by coolryze** [codingZero/XRCarouselView#36]
你好，我使用你的代码做轮播图，在外部修改 XRCarouselView 的 frame 后，手动从右往左滑，pageControl 位置计算错乱，从左往右是没问题的。
感觉应该是 changeCurrentPageWithOffset 方法的问题，但目前还没看懂你是怎样计算的。

**Comment by codingZero** [comment]
不太理解你的意思，是pageControl的frame发生了变化，还是说当前页码显示不准？

**Comment by coolryze** [comment]
页码显示不准，但现在找到问题了，是我这边处理不当~ 
谢谢你，XRCarouselView非常好用  ：）
