### ISSUE TITLE
我把你封装的滚动视图，放到tableViewcell里面后，不能实现拖动了，但是自己还是可以滚动

### ISSUE THREAD

**Issue by zengwen0929** [codingZero/XRCarouselView#4]
我把你封装的滚动视图，放到tableViewcell里面后，不能实现拖动了，但是自己还是可以滚动

**Comment by codingZero** [comment]
你好，我刚刚特意试了一下，手动自动都可以滚动，是不是你给cell加了其他滑动的事件，所以导致手动轮播失效了？

**Comment by codingZero** [comment]
@zengwen0929 你好，我刚刚特意试了一下，手动自动都可以滚动，是不是你给cell加了其他滑动的事件，所以导致手动轮播失效了？

**Comment by zengwen0929** [comment]
我这边应该没有添加其他的滑动事件。 能留个邮箱吗？我发代码给你帮我看看，谢谢。

**Comment by codingZero** [comment]
yd13150@vip.qq.com

**Comment by codingZero** [comment]
@zengwen0929 yd13150@vip.qq.com
