### ISSUE TITLE
issue: pod 无法导入 找不到组件 ps:非常感谢您的文章

### ISSUE THREAD

**Issue by onepiece502** [codingZero/XRCarouselView#5]
pod 报错

> Unable to find a specification for `XRCarouselView (~> 2.3.1)`
>  ps:非常感谢您的文章

**Comment by codingZero** [comment]
@onepiece1992  你好，我这边刚刚测试了一下，成功导入，没有你说的那个问题，会不会是因为你哪里误操作了
