### ISSUE TITLE
发现3个bug

### ISSUE THREAD

**Issue by Jenova4582** [codingZero/XRCarouselView#6]
使用时发现3个bug
1.自定义了切换时间后,还是会出现变成默认2s的情况.
2.从网络加载完图片后,不能及时替代占位图显示出来.
3.首次加载数据,直接向左划会crash.

已经手动修改代码解决,也不排除是使用方法不对导致的问题.
有时间你可以看一下.

**Comment by codingZero** [comment]
@Jenova4582 你好，关于第一点，需要在设置图片数组之后设置时间，当然这一点不太友好，有空我会改进
第二点，这个问题我已修复，等第一点解决后一起提交
第三点，我试了一下没有发现这个问题，你是使用的最新版本吗？

**Comment by Jenova4582** [comment]
关于第三点,确实demo是没有问题的,可能是我工程中有些冲突.
祝越做越好.

**Comment by codingZero** [comment]
@Jenova4582 前两个问题我刚刚已经修复了，谢谢你的反馈，欢迎使用

**Comment by ghost** [comment]
@codingZero     你好，在使用XRCarouselView同样遇到了首次加载数据的时候，手指右划时或者图片左划时会crash的问题。

在`- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *, id> *)change context:(void *)context;
`这个方法中，首次加载数据后手指向右划动时会直接给`self.otherImageView.image`赋值，而此时并没有判断self.nextIndex是否小于零，会导致数组越界崩溃。

稍微修改了一下，仅供参考:
![snip20160411_1](https://cloud.githubusercontent.com/assets/11835866/14418392/c8a28758-fff0-11e5-9f8b-25cbdf5eeedb.png)

**Comment by codingZero** [comment]
@samxxy 你好，谢谢反馈，该bug之前已经修复了，你这个不是最新版

**Comment by TYQbag** [comment]
使用时发现一个bug，当只有一张网络图片被加载时，图片的点击事件没有了，但是加载一张以上的图片点击事件倒是没问题

**Comment by codingZero** [comment]
@TYQbag 我这边试了一下，没有你说的问题，能把你代码发我吗？yd13150@vip.qq.com

**Comment by TYQbag** [comment]
应该这样说，在加载轮播图的界面进行页面跳转，再次跳转回轮播图界面就会出现点击失效的情况，前提是只加载一张网络图片的情况

**Comment by codingZero** [comment]
@TYQbag 谢谢你的反馈，这个bug还真不好发现，已修复，欢迎下载最新版使用
