### ISSUE TITLE
在有URL，但是请求不到图片的时候，会崩溃。

### ISSUE THREAD

**Issue by monarchofnaonao** [codingZero/XRCarouselView#7]
你好：
          在开发中，其实可能会出现这种问题，有url，但是个错误的url。
          这个时候，本地缓存没有。下载图片下载不到的时候，会crash。
                      *\*  UIImage _image = [UIImage imageWithData:data];
                          [self.imageDic setObject:image forKey:key];_*
          代码是这两句，因为image是个空的，所以存储的时候，就会cras掉。
        不知道你们有没有过这种问题，我是碰到过。如果说的不对，还请见谅。

**Comment by codingZero** [comment]
@monarchofnaonao 谢谢反馈，我的代码里之前有判断，只有data存在的时候才会执行下面的代码，你说的这种情况，估计是data有值，但是又不是图片，比如网页，文件什么的，为了安全起见，又对image加了一个判断，已更新。
