### ISSUE TITLE
延迟设置图片数组无法正常显示

### ISSUE THREAD

**Issue by tunghee** [codingZero/XRCarouselView#8]
你好。
我先创建一个XRCarouselView（传的空图片数组），然后通过网络请求图片地址，再将图片地址数组赋值给imagesArray，发现这样赋值无法正常显示，上一个版本都可以的。

**Comment by codingZero** [comment]
你的意思是，创建的时候给imageArray传nil，等拿到图片地址了再设置imageArray无效是吗？

**Comment by codingZero** [comment]
@tunghee 你的意思是，创建的时候给imageArray传nil，等拿到图片地址了再设置imageArray无效是吗？

**Comment by tunghee** [comment]
@codingZero 是的

**Comment by codingZero** [comment]
@tunghee 直接在源代码的setImageArray方法的最后面加上一句[self layoutSubviews];就可以了，或者你等下重新下载最新版

**Comment by tunghee** [comment]
@codingZero 好的，非常感谢

**Comment by tunghee** [comment]
@codingZero 刷新的时候总是会显示第一张图片，不管正在显示的是否是第一张，我的做法是加了个判断

**Comment by codingZero** [comment]
@tunghee 你好，不太明白你的意思，你的刷新指什么？

**Comment by tunghee** [comment]
@codingZero 比如滚到第三张图片的时候，我重新设置图片数据源，这时候第三张图片显示的是第一张。其实问题就是当时看到的不管是第几张图片，当我重新设置图片数据源的时候都会变成第一张图片，但是其实不应该显示第一张。

**Comment by codingZero** [comment]
@tunghee 已修复，谢谢反馈
